version: "3.8"

services:
  nginx:
    image: nginx:alpine
    ports:
      - "3000:3000"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./logs:/var/log/nginx
    networks:
      - app-network
    depends_on:
      - master
      - na_1
      - na_2
      - eu_1
      - eu_2

  master:
    build: .
    environment:
      - REGION=master
      - PORT=3001
      - MASTER_DB_PORT=1533
    ports:
      - "3001:3001"
    networks:
      - app-network

  na_1:
    build: .
    environment:
      - REGION=na
      - PORT=3002
      - NA_DB_PORT=1535
      - MASTER_DB_PORT=1533
    networks:
      - app-network

  na_2:
    build: .
    environment:
      - REGION=na
      - PORT=3003
      - NA_DB_PORT=1535
      - MASTER_DB_PORT=1533
    networks:
      - app-network

  eu_1:
    build: .
    environment:
      - REGION=eu
      - PORT=3004
      - EU_DB_PORT=1536
      - MASTER_DB_PORT=1533
    networks:
      - app-network

  eu_2:
    build: .
    environment:
      - REGION=eu
      - PORT=3005
      - EU_DB_PORT=1536
      - MASTER_DB_PORT=1533
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  logs:
